### ISSUE TITLE
编译cnws失败

### ISSUE THREAD

**Issue by beast-pro** [kanglmf/emacs-chinese-word-segmentation#2]
## 报错信息
```bash
-> % make
g++ -Icppjieba/deps/limonp/include -Icppjieba/include -O3 -o cnws cnws.cpp
cnws.cpp:12:21: error: no member named '__fs' in namespace 'std'
namespace fs = std::__fs::filesystem;
               ~~~~~^
cnws.cpp:56:3: error: use of undeclared identifier 'fs'
  fs::path dir (argv[1]);
  ^
....
```
## clang版本
```bash

-> % g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: arm64-apple-darwin21.4.0
Thread model: posix
```

尝试使用 `-std=c++17`，依旧失败

```bash
-> % g++ -std=c++17 -Icppjieba/deps/limonp/include -Icppjieba/include -O3 -o cnws cnws.cpp
In file included from cnws.cpp:17:
In file included from cppjieba/include/cppjieba/DictTrie.hpp:13:
cppjieba/deps/limonp/include/limonp/StringUtil.hpp:87:70: error: no member named 'ptr_fun' in namespace 'std'
  s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not1(std::ptr_fun<unsigned, bool>(IsSpace))));
```

**Comment by kanglmf** [comment]
由于[C++ std::filesystem 的问题](https://zhuanlan.zhihu.com/p/365987461)，已尝试修复，若仍无法编译请告知，或直接发起PR，谢谢。

**Comment by beast-pro** [comment]
@kanglmf 问题仍然存在
![image](https://user-images.githubusercontent.com/116860578/203705268-76f38dea-c582-47ce-a61c-ed618275ec78.png)
我看了一下你的修复，从判断是否是clang换成了是否是Android？但是我用的是M1的mac，我尝试加上了 `-std=c++17` 换成了 cppjieba 报错
![image](https://user-images.githubusercontent.com/116860578/203705791-89496096-bdf8-4925-a146-ac5caf4ecff6.png)
仓库版本
![image](https://user-images.githubusercontent.com/116860578/203706750-8bf95dc5-c5d5-4645-8fcf-29f6c66947be.png)
系统版本
![image](https://user-images.githubusercontent.com/116860578/203707213-56c42f53-01d8-4494-839f-b6e522b47482.png)



ps：
不尝试自己修复再提PR的原因是，我只会一点其它语言，c++的报错和诊断是连蒙带猜的，真要上手修改确实有点无从下手

**Comment by kanglmf** [comment]
主要是 std::filesystem 的问题，很遗憾 Mac 平台我从未用过，请参考网上资源（例如[此处](https://stackoverflow.com/questions/49577343/filesystem-with-c17-doesnt-work-on-my-mac-os-x-high-sierra) ）来测试 Mac 平台，希望能解决问题。

**Comment by kanglmf** [comment]
已修改为在 elisp 中解析文件路径，这样编译问题应该能解决。

**Comment by beast-pro** [comment]
在mac已经能正常使用，非常感谢

**Comment by beast-pro** [comment]
在mac已经能正常使用，非常感谢
