### ISSUE TITLE
cns-forward-word 跳英文会往前一个空格

### ISSUE THREAD

**Issue by C1oud555** [kanglmf/emacs-chinese-word-segmentation#3]
rt，环境是mac下的emacs-plus

同时希望能有一个配合doom-emacs中的evil使用的教程

**Comment by C1oud555** [comment]
在想后端换成 jieba-rs 会不会性能更好

**Comment by kanglmf** [comment]
> rt，环境是mac下的emacs-plus
> 
> 同时希望能有一个配合doom-emacs中的evil使用的教程

请具体描述问题，如移动之前位于中文还是英文处，你的环境是否有`post-command-hook`或`defadvice`等可能影响移动操作的设置，若有截图或GIF演示过程更好。

**Comment by kanglmf** [comment]
> 在想后端换成 jieba-rs 会不会性能更好

请见readme，后端可以使用任何软件，只需输出正确格式的分词信息即可，可以在加载`cns.el`之前设置好`cns-process-shell-command`，这样就会使用自定义的分词软件。本人若有精力也可能考虑改进后端实现。感谢建议。

**Comment by C1oud555** [comment]
> > rt，环境是mac下的emacs-plus
> > 同时希望能有一个配合doom-emacs中的evil使用的教程
> 
> 请具体描述问题，如移动之前位于中文还是英文处，你的环境是否有`post-command-hook`或`defadvice`等可能影响移动操作的设置，若有截图或GIF演示过程更好。

![fencibug](https://user-images.githubusercontent.com/39260955/221087128-aff2b293-4fe9-4b15-9d66-5621544bb6df.gif)

我用的是doom emacs，感觉里面应该有很多defadvice

**Comment by C1oud555** [comment]
我试着照着cnws.cpp写了一个rust的wrapper，看了一下结果。感觉是分词系统在处理英文的时候会把空格单独分割出来造成的错位。

<img width="459" alt="截屏2023-02-24 17 21 13" src="https://user-images.githubusercontent.com/39260955/221141264-83f76f37-4ebe-4bc9-84b6-a46f490d59fe.png">

**Comment by kanglmf** [comment]
未用过doom，本软件包在光标位于英文时（包括移动前和移动后）不进行分词，直接执行`forward-word`/`backward-word`，所以示例中的`englist test`一行的移动行为应该不是本软件包所导致的。看 gif 最后一行是正确的中文词语移动。建议通过以下方式查找原因：(1) 用`emacs -q`方式启动并加载`cns.el`，看中文移动是否正确；(2) 看`cns-process-buffer`中的分词结果是否正确，可以通过`split-window`方式实时查看分词结果，包括英文移动时是否也有（错误的）分词产生。

**Comment by kanglmf** [comment]
> 我试着照着cnws.cpp写了一个rust的wrapper，看了一下结果。感觉是分词系统在处理英文的时候会把空格单独分割出来造成的错位。

若用其它分词软件，请只用中文汉字做为input进行测试，不应包含英文，本软件包也不会将英文（以及中、英文标点符号）发送给分词软件，目的是不额外增加处理非汉字字符的过程。
